# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.patch_release_upload_status_request import PatchReleaseUploadStatusRequest  # noqa: E501
from appcenter.rest import ApiException


class TestPatchReleaseUploadStatusRequest(unittest.TestCase):
    """PatchReleaseUploadStatusRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchReleaseUploadStatusRequest(self):
        """Test PatchReleaseUploadStatusRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.patch_release_upload_status_request.PatchReleaseUploadStatusRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
