# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.event_count_per_session import EventCountPerSession  # noqa: E501
from appcenter.rest import ApiException


class TestEventCountPerSession(unittest.TestCase):
    """EventCountPerSession unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventCountPerSession(self):
        """Test EventCountPerSession"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.event_count_per_session.EventCountPerSession()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
