# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.release_upload_end_response import ReleaseUploadEndResponse  # noqa: E501
from appcenter.rest import ApiException


class TestReleaseUploadEndResponse(unittest.TestCase):
    """ReleaseUploadEndResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReleaseUploadEndResponse(self):
        """Test ReleaseUploadEndResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.release_upload_end_response.ReleaseUploadEndResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
