# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from api.alerting_api import AlertingApi  # noqa: E501
from appcenter.rest import ApiException


class TestAlertingApi(unittest.TestCase):
    """AlertingApi unit test stubs"""

    def setUp(self):
        self.api = api.alerting_api.AlertingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_bug_tracker_get_repo_issue_from_crash(self):
        """Test case for bug_tracker_get_repo_issue_from_crash

        """
        pass

    def test_bugtracker_get_settings(self):
        """Test case for bugtracker_get_settings

        """
        pass

    def test_notifications_get_app_email_settings(self):
        """Test case for notifications_get_app_email_settings

        """
        pass

    def test_notifications_get_user_email_settings(self):
        """Test case for notifications_get_user_email_settings

        """
        pass

    def test_webhooks_list(self):
        """Test case for webhooks_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
