# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.generic_log_diagnostics import GenericLogDiagnostics  # noqa: E501
from appcenter.rest import ApiException


class TestGenericLogDiagnostics(unittest.TestCase):
    """GenericLogDiagnostics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGenericLogDiagnostics(self):
        """Test GenericLogDiagnostics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.generic_log_diagnostics.GenericLogDiagnostics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
