# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.patch_repo_info import PatchRepoInfo  # noqa: E501
from appcenter.rest import ApiException


class TestPatchRepoInfo(unittest.TestCase):
    """PatchRepoInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPatchRepoInfo(self):
        """Test PatchRepoInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.patch_repo_info.PatchRepoInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
