# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.test_cloud_project_framework_properties import TestCloudProjectFrameworkProperties  # noqa: E501
from appcenter.rest import ApiException


class TestTestCloudProjectFrameworkProperties(unittest.TestCase):
    """TestCloudProjectFrameworkProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestCloudProjectFrameworkProperties(self):
        """Test TestCloudProjectFrameworkProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.test_cloud_project_framework_properties.TestCloudProjectFrameworkProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
