# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.jira_secret_details_response import JiraSecretDetailsResponse  # noqa: E501
from appcenter.rest import ApiException


class TestJiraSecretDetailsResponse(unittest.TestCase):
    """JiraSecretDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJiraSecretDetailsResponse(self):
        """Test JiraSecretDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.jira_secret_details_response.JiraSecretDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
