# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.distribution_group_aad_groups_delete_request import DistributionGroupAADGroupsDeleteRequest  # noqa: E501
from appcenter.rest import ApiException


class TestDistributionGroupAADGroupsDeleteRequest(unittest.TestCase):
    """DistributionGroupAADGroupsDeleteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistributionGroupAADGroupsDeleteRequest(self):
        """Test DistributionGroupAADGroupsDeleteRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.distribution_group_aad_groups_delete_request.DistributionGroupAADGroupsDeleteRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
