# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.message_envelope import MessageEnvelope  # noqa: E501
from appcenter.rest import ApiException


class TestMessageEnvelope(unittest.TestCase):
    """MessageEnvelope unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageEnvelope(self):
        """Test MessageEnvelope"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.message_envelope.MessageEnvelope()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
