# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.apple_connection_non_secret_response import AppleConnectionNonSecretResponse  # noqa: E501
from appcenter.rest import ApiException


class TestAppleConnectionNonSecretResponse(unittest.TestCase):
    """AppleConnectionNonSecretResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppleConnectionNonSecretResponse(self):
        """Test AppleConnectionNonSecretResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.apple_connection_non_secret_response.AppleConnectionNonSecretResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
