# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.release_upload_begin_request import ReleaseUploadBeginRequest  # noqa: E501
from appcenter.rest import ApiException


class TestReleaseUploadBeginRequest(unittest.TestCase):
    """ReleaseUploadBeginRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReleaseUploadBeginRequest(self):
        """Test ReleaseUploadBeginRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.release_upload_begin_request.ReleaseUploadBeginRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
