# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.distribution_group_response import DistributionGroupResponse  # noqa: E501
from appcenter.rest import ApiException


class TestDistributionGroupResponse(unittest.TestCase):
    """DistributionGroupResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDistributionGroupResponse(self):
        """Test DistributionGroupResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.distribution_group_response.DistributionGroupResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
