# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.log_with_properties import LogWithProperties  # noqa: E501
from appcenter.rest import ApiException


class TestLogWithProperties(unittest.TestCase):
    """LogWithProperties unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogWithProperties(self):
        """Test LogWithProperties"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.log_with_properties.LogWithProperties()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
