# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.test_run_statistics import TestRunStatistics  # noqa: E501
from appcenter.rest import ApiException


class TestTestRunStatistics(unittest.TestCase):
    """TestRunStatistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestRunStatistics(self):
        """Test TestRunStatistics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.test_run_statistics.TestRunStatistics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
