# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.apple_connection_secret_response import AppleConnectionSecretResponse  # noqa: E501
from appcenter.rest import ApiException


class TestAppleConnectionSecretResponse(unittest.TestCase):
    """AppleConnectionSecretResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppleConnectionSecretResponse(self):
        """Test AppleConnectionSecretResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.apple_connection_secret_response.AppleConnectionSecretResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
