# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from api.test_api import TestApi  # noqa: E501
from appcenter.rest import ApiException


class TestTestApi(unittest.TestCase):
    """TestApi unit test stubs"""

    def setUp(self):
        self.api = api.test_api.TestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_test_archive_test_run(self):
        """Test case for test_archive_test_run

        """
        pass

    def test_test_create_device_selection(self):
        """Test case for test_create_device_selection

        """
        pass

    def test_test_create_device_set_of_owner(self):
        """Test case for test_create_device_set_of_owner

        """
        pass

    def test_test_create_device_set_of_user(self):
        """Test case for test_create_device_set_of_user

        """
        pass

    def test_test_create_subscription(self):
        """Test case for test_create_subscription

        """
        pass

    def test_test_create_test_run(self):
        """Test case for test_create_test_run

        """
        pass

    def test_test_create_test_series(self):
        """Test case for test_create_test_series

        """
        pass

    def test_test_delete_device_set_of_owner(self):
        """Test case for test_delete_device_set_of_owner

        """
        pass

    def test_test_delete_device_set_of_user(self):
        """Test case for test_delete_device_set_of_user

        """
        pass

    def test_test_delete_test_series(self):
        """Test case for test_delete_test_series

        """
        pass

    def test_test_gdpr_export_account(self):
        """Test case for test_gdpr_export_account

        """
        pass

    def test_test_gdpr_export_accounts(self):
        """Test case for test_gdpr_export_accounts

        """
        pass

    def test_test_gdpr_export_apps(self):
        """Test case for test_gdpr_export_apps

        """
        pass

    def test_test_gdpr_export_feature_flag(self):
        """Test case for test_gdpr_export_feature_flag

        """
        pass

    def test_test_gdpr_export_file_set_file(self):
        """Test case for test_gdpr_export_file_set_file

        """
        pass

    def test_test_gdpr_export_hash_file(self):
        """Test case for test_gdpr_export_hash_file

        """
        pass

    def test_test_gdpr_export_pipeline_test(self):
        """Test case for test_gdpr_export_pipeline_test

        """
        pass

    def test_test_gdpr_export_test_run(self):
        """Test case for test_gdpr_export_test_run

        """
        pass

    def test_test_get_all_test_runs_for_series(self):
        """Test case for test_get_all_test_runs_for_series

        """
        pass

    def test_test_get_all_test_series(self):
        """Test case for test_get_all_test_series

        """
        pass

    def test_test_get_device_configurations(self):
        """Test case for test_get_device_configurations

        """
        pass

    def test_test_get_device_set_of_owner(self):
        """Test case for test_get_device_set_of_owner

        """
        pass

    def test_test_get_device_set_of_user(self):
        """Test case for test_get_device_set_of_user

        """
        pass

    def test_test_get_subscriptions(self):
        """Test case for test_get_subscriptions

        """
        pass

    def test_test_get_test_report(self):
        """Test case for test_get_test_report

        """
        pass

    def test_test_get_test_run(self):
        """Test case for test_get_test_run

        """
        pass

    def test_test_get_test_run_state(self):
        """Test case for test_get_test_run_state

        """
        pass

    def test_test_get_test_runs(self):
        """Test case for test_get_test_runs

        """
        pass

    def test_test_list_device_sets_of_owner(self):
        """Test case for test_list_device_sets_of_owner

        """
        pass

    def test_test_list_device_sets_of_user(self):
        """Test case for test_list_device_sets_of_user

        """
        pass

    def test_test_patch_test_series(self):
        """Test case for test_patch_test_series

        """
        pass

    def test_test_start_test_run(self):
        """Test case for test_start_test_run

        """
        pass

    def test_test_start_uploading_file(self):
        """Test case for test_start_uploading_file

        """
        pass

    def test_test_stop_test_run(self):
        """Test case for test_stop_test_run

        """
        pass

    def test_test_update_device_set_of_owner(self):
        """Test case for test_update_device_set_of_owner

        """
        pass

    def test_test_update_device_set_of_user(self):
        """Test case for test_update_device_set_of_user

        """
        pass

    def test_test_upload_hash(self):
        """Test case for test_upload_hash

        """
        pass

    def test_test_upload_hashes_batch(self):
        """Test case for test_upload_hashes_batch

        """
        pass


if __name__ == '__main__':
    unittest.main()
