# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.v2_failure_response import V2FailureResponse  # noqa: E501
from appcenter.rest import ApiException


class TestV2FailureResponse(unittest.TestCase):
    """V2FailureResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2FailureResponse(self):
        """Test V2FailureResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.v2_failure_response.V2FailureResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
