# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.user_invitation_permissions_update_request import UserInvitationPermissionsUpdateRequest  # noqa: E501
from appcenter.rest import ApiException


class TestUserInvitationPermissionsUpdateRequest(unittest.TestCase):
    """UserInvitationPermissionsUpdateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserInvitationPermissionsUpdateRequest(self):
        """Test UserInvitationPermissionsUpdateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.user_invitation_permissions_update_request.UserInvitationPermissionsUpdateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
