# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.create_store_secret_response import CreateStoreSecretResponse  # noqa: E501
from appcenter.rest import ApiException


class TestCreateStoreSecretResponse(unittest.TestCase):
    """CreateStoreSecretResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateStoreSecretResponse(self):
        """Test CreateStoreSecretResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.create_store_secret_response.CreateStoreSecretResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
