# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.reason_stack_frame import ReasonStackFrame  # noqa: E501
from appcenter.rest import ApiException


class TestReasonStackFrame(unittest.TestCase):
    """ReasonStackFrame unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReasonStackFrame(self):
        """Test ReasonStackFrame"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.reason_stack_frame.ReasonStackFrame()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
