# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.file_validation_details import FileValidationDetails  # noqa: E501
from appcenter.rest import ApiException


class TestFileValidationDetails(unittest.TestCase):
    """FileValidationDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFileValidationDetails(self):
        """Test FileValidationDetails"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.file_validation_details.FileValidationDetails()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
