# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.device_diagnostics import DeviceDiagnostics  # noqa: E501
from appcenter.rest import ApiException


class TestDeviceDiagnostics(unittest.TestCase):
    """DeviceDiagnostics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceDiagnostics(self):
        """Test DeviceDiagnostics"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.device_diagnostics.DeviceDiagnostics()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
