# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.v2_missing_symbol_crash_group_status_enum import V2MissingSymbolCrashGroupStatusEnum  # noqa: E501
from appcenter.rest import ApiException


class TestV2MissingSymbolCrashGroupStatusEnum(unittest.TestCase):
    """V2MissingSymbolCrashGroupStatusEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV2MissingSymbolCrashGroupStatusEnum(self):
        """Test V2MissingSymbolCrashGroupStatusEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.v2_missing_symbol_crash_group_status_enum.V2MissingSymbolCrashGroupStatusEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
