# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.tester_app_with_release_response import TesterAppWithReleaseResponse  # noqa: E501
from appcenter.rest import ApiException


class TestTesterAppWithReleaseResponse(unittest.TestCase):
    """TesterAppWithReleaseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTesterAppWithReleaseResponse(self):
        """Test TesterAppWithReleaseResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.tester_app_with_release_response.TesterAppWithReleaseResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
