# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.session_durations_distribution import SessionDurationsDistribution  # noqa: E501
from appcenter.rest import ApiException


class TestSessionDurationsDistribution(unittest.TestCase):
    """SessionDurationsDistribution unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSessionDurationsDistribution(self):
        """Test SessionDurationsDistribution"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.session_durations_distribution.SessionDurationsDistribution()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
