# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.google_play_connection_secret_response import GooglePlayConnectionSecretResponse  # noqa: E501
from appcenter.rest import ApiException


class TestGooglePlayConnectionSecretResponse(unittest.TestCase):
    """GooglePlayConnectionSecretResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGooglePlayConnectionSecretResponse(self):
        """Test GooglePlayConnectionSecretResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.google_play_connection_secret_response.GooglePlayConnectionSecretResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
