# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.apple_certificate_non_secret_details_response import AppleCertificateNonSecretDetailsResponse  # noqa: E501
from appcenter.rest import ApiException


class TestAppleCertificateNonSecretDetailsResponse(unittest.TestCase):
    """AppleCertificateNonSecretDetailsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppleCertificateNonSecretDetailsResponse(self):
        """Test AppleCertificateNonSecretDetailsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.apple_certificate_non_secret_details_response.AppleCertificateNonSecretDetailsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
