# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.code_push_release_promote import CodePushReleasePromote  # noqa: E501
from appcenter.rest import ApiException


class TestCodePushReleasePromote(unittest.TestCase):
    """CodePushReleasePromote unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCodePushReleasePromote(self):
        """Test CodePushReleasePromote"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.code_push_release_promote.CodePushReleasePromote()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
