# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.crash_attachment import CrashAttachment  # noqa: E501
from appcenter.rest import ApiException


class TestCrashAttachment(unittest.TestCase):
    """CrashAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCrashAttachment(self):
        """Test CrashAttachment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.crash_attachment.CrashAttachment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
