# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.unhandled_error_log import UnhandledErrorLog  # noqa: E501
from appcenter.rest import ApiException


class TestUnhandledErrorLog(unittest.TestCase):
    """UnhandledErrorLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnhandledErrorLog(self):
        """Test UnhandledErrorLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.unhandled_error_log.UnhandledErrorLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
