# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.organization_invitation_detail_response import OrganizationInvitationDetailResponse  # noqa: E501
from appcenter.rest import ApiException


class TestOrganizationInvitationDetailResponse(unittest.TestCase):
    """OrganizationInvitationDetailResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationInvitationDetailResponse(self):
        """Test OrganizationInvitationDetailResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.organization_invitation_detail_response.OrganizationInvitationDetailResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
