# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.get_in_app_update_token_response import GetInAppUpdateTokenResponse  # noqa: E501
from appcenter.rest import ApiException


class TestGetInAppUpdateTokenResponse(unittest.TestCase):
    """GetInAppUpdateTokenResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetInAppUpdateTokenResponse(self):
        """Test GetInAppUpdateTokenResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.get_in_app_update_token_response.GetInAppUpdateTokenResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
