# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.release_destination_response import ReleaseDestinationResponse  # noqa: E501
from appcenter.rest import ApiException


class TestReleaseDestinationResponse(unittest.TestCase):
    """ReleaseDestinationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReleaseDestinationResponse(self):
        """Test ReleaseDestinationResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.release_destination_response.ReleaseDestinationResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
