# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.tier import Tier  # noqa: E501
from appcenter.rest import ApiException


class TestTier(unittest.TestCase):
    """Tier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTier(self):
        """Test Tier"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.tier.Tier()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
