# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.git_hub_pull_request_lite import GitHubPullRequestLite  # noqa: E501
from appcenter.rest import ApiException


class TestGitHubPullRequestLite(unittest.TestCase):
    """GitHubPullRequestLite unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGitHubPullRequestLite(self):
        """Test GitHubPullRequestLite"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.git_hub_pull_request_lite.GitHubPullRequestLite()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
