# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.event_log import EventLog  # noqa: E501
from appcenter.rest import ApiException


class TestEventLog(unittest.TestCase):
    """EventLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEventLog(self):
        """Test EventLog"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.event_log.EventLog()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
