# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.private_google_play_connection_secret_response import PrivateGooglePlayConnectionSecretResponse  # noqa: E501
from appcenter.rest import ApiException


class TestPrivateGooglePlayConnectionSecretResponse(unittest.TestCase):
    """PrivateGooglePlayConnectionSecretResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrivateGooglePlayConnectionSecretResponse(self):
        """Test PrivateGooglePlayConnectionSecretResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.private_google_play_connection_secret_response.PrivateGooglePlayConnectionSecretResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
