# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.legacy_patch_deployment_response import LegacyPatchDeploymentResponse  # noqa: E501
from appcenter.rest import ApiException


class TestLegacyPatchDeploymentResponse(unittest.TestCase):
    """LegacyPatchDeploymentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLegacyPatchDeploymentResponse(self):
        """Test LegacyPatchDeploymentResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.legacy_patch_deployment_response.LegacyPatchDeploymentResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
