# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from api.mbaas_api import MbaasApi  # noqa: E501
from appcenter.rest import ApiException


class TestMbaasApi(unittest.TestCase):
    """MbaasApi unit test stubs"""

    def setUp(self):
        self.api = api.mbaas_api.MbaasApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_check_name_exists(self):
        """Test case for data_check_name_exists

        Checks that the Azure Cosmos DB account name already exists. A valid account name may contain only lowercase letters, numbers, and the '-' character, and must be between 3 and 31 characters.  # noqa: E501
        """
        pass

    def test_data_get_overview(self):
        """Test case for data_get_overview

        Gets general data about the provisioned database  # noqa: E501
        """
        pass

    def test_data_get_resource_provisioning(self):
        """Test case for data_get_resource_provisioning

        """
        pass

    def test_data_post_resource_provisioning(self):
        """Test case for data_post_resource_provisioning

        Creates Cosmos DB or attaches an existing one  # noqa: E501
        """
        pass

    def test_identity_get_users(self):
        """Test case for identity_get_users

        Returns users of a tenant. Returns all users if no searchTerm param is specified.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
