# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.billing_plans_change_type_response import BillingPlansChangeTypeResponse  # noqa: E501
from appcenter.rest import ApiException


class TestBillingPlansChangeTypeResponse(unittest.TestCase):
    """BillingPlansChangeTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillingPlansChangeTypeResponse(self):
        """Test BillingPlansChangeTypeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.billing_plans_change_type_response.BillingPlansChangeTypeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
