# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.org_compliance_settings_response import OrgComplianceSettingsResponse  # noqa: E501
from appcenter.rest import ApiException


class TestOrgComplianceSettingsResponse(unittest.TestCase):
    """OrgComplianceSettingsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrgComplianceSettingsResponse(self):
        """Test OrgComplianceSettingsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.org_compliance_settings_response.OrgComplianceSettingsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
