# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.api_token_responsev2 import ApiTokenResponsev2  # noqa: E501
from appcenter.rest import ApiException


class TestApiTokenResponsev2(unittest.TestCase):
    """ApiTokenResponsev2 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiTokenResponsev2(self):
        """Test ApiTokenResponsev2"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.api_token_responsev2.ApiTokenResponsev2()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
