# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import appcenter
from models.hockey_app_compatibility_release_response import HockeyAppCompatibilityReleaseResponse  # noqa: E501
from appcenter.rest import ApiException


class TestHockeyAppCompatibilityReleaseResponse(unittest.TestCase):
    """HockeyAppCompatibilityReleaseResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHockeyAppCompatibilityReleaseResponse(self):
        """Test HockeyAppCompatibilityReleaseResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = appcenter.models.hockey_app_compatibility_release_response.HockeyAppCompatibilityReleaseResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
