# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AvailableAppBuilds(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'app_builds': 'list[str]'
    }

    attribute_map = {
        'app_builds': 'app_builds'
    }

    def __init__(self, app_builds=None):  # noqa: E501
        """AvailableAppBuilds - a model defined in Swagger"""  # noqa: E501
        self._app_builds = None
        self.discriminator = None
        if app_builds is not None:
            self.app_builds = app_builds

    @property
    def app_builds(self):
        """Gets the app_builds of this AvailableAppBuilds.  # noqa: E501

        List of available app builds.  # noqa: E501

        :return: The app_builds of this AvailableAppBuilds.  # noqa: E501
        :rtype: list[str]
        """
        return self._app_builds

    @app_builds.setter
    def app_builds(self, app_builds):
        """Sets the app_builds of this AvailableAppBuilds.

        List of available app builds.  # noqa: E501

        :param app_builds: The app_builds of this AvailableAppBuilds.  # noqa: E501
        :type: list[str]
        """

        self._app_builds = app_builds

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AvailableAppBuilds, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AvailableAppBuilds):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
