# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class DataResourceTokenResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'database_name': 'str',
        'collection_name': 'str',
        'account_name': 'str',
        'token': 'str'
    }

    attribute_map = {
        'database_name': 'databaseName',
        'collection_name': 'collectionName',
        'account_name': 'accountName',
        'token': 'token'
    }

    def __init__(self, database_name=None, collection_name=None, account_name=None, token=None):  # noqa: E501
        """DataResourceTokenResponse - a model defined in Swagger"""  # noqa: E501
        self._database_name = None
        self._collection_name = None
        self._account_name = None
        self._token = None
        self.discriminator = None
        if database_name is not None:
            self.database_name = database_name
        if collection_name is not None:
            self.collection_name = collection_name
        if account_name is not None:
            self.account_name = account_name
        if token is not None:
            self.token = token

    @property
    def database_name(self):
        """Gets the database_name of this DataResourceTokenResponse.  # noqa: E501


        :return: The database_name of this DataResourceTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._database_name

    @database_name.setter
    def database_name(self, database_name):
        """Sets the database_name of this DataResourceTokenResponse.


        :param database_name: The database_name of this DataResourceTokenResponse.  # noqa: E501
        :type: str
        """

        self._database_name = database_name

    @property
    def collection_name(self):
        """Gets the collection_name of this DataResourceTokenResponse.  # noqa: E501


        :return: The collection_name of this DataResourceTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._collection_name

    @collection_name.setter
    def collection_name(self, collection_name):
        """Sets the collection_name of this DataResourceTokenResponse.


        :param collection_name: The collection_name of this DataResourceTokenResponse.  # noqa: E501
        :type: str
        """

        self._collection_name = collection_name

    @property
    def account_name(self):
        """Gets the account_name of this DataResourceTokenResponse.  # noqa: E501


        :return: The account_name of this DataResourceTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._account_name

    @account_name.setter
    def account_name(self, account_name):
        """Sets the account_name of this DataResourceTokenResponse.


        :param account_name: The account_name of this DataResourceTokenResponse.  # noqa: E501
        :type: str
        """

        self._account_name = account_name

    @property
    def token(self):
        """Gets the token of this DataResourceTokenResponse.  # noqa: E501


        :return: The token of this DataResourceTokenResponse.  # noqa: E501
        :rtype: str
        """
        return self._token

    @token.setter
    def token(self, token):
        """Sets the token of this DataResourceTokenResponse.


        :param token: The token of this DataResourceTokenResponse.  # noqa: E501
        :type: str
        """

        self._token = token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DataResourceTokenResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DataResourceTokenResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
