# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from appcenter.models.distribution_store_without_is_latest import DistributionStoreWithoutIsLatest  # noqa: F401,E501


class DistributionStore(DistributionStoreWithoutIsLatest):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'is_latest': 'bool'
    }
    if hasattr(DistributionStoreWithoutIsLatest, "swagger_types"):
        swagger_types.update(DistributionStoreWithoutIsLatest.swagger_types)

    attribute_map = {
        'is_latest': 'is_latest'
    }
    if hasattr(DistributionStoreWithoutIsLatest, "attribute_map"):
        attribute_map.update(DistributionStoreWithoutIsLatest.attribute_map)

    def __init__(self, is_latest=None, *args, **kwargs):  # noqa: E501
        """DistributionStore - a model defined in Swagger"""  # noqa: E501
        self._is_latest = None
        self.discriminator = None
        if is_latest is not None:
            self.is_latest = is_latest
        DistributionStoreWithoutIsLatest.__init__(self, *args, **kwargs)

    @property
    def is_latest(self):
        """Gets the is_latest of this DistributionStore.  # noqa: E501

        Is the containing release the latest one in this distribution store.  # noqa: E501

        :return: The is_latest of this DistributionStore.  # noqa: E501
        :rtype: bool
        """
        return self._is_latest

    @is_latest.setter
    def is_latest(self, is_latest):
        """Sets the is_latest of this DistributionStore.

        Is the containing release the latest one in this distribution store.  # noqa: E501

        :param is_latest: The is_latest of this DistributionStore.  # noqa: E501
        :type: bool
        """

        self._is_latest = is_latest

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DistributionStore, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DistributionStore):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
