# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class JiraSecretDetails(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'base_url': 'str',
        'username': 'str',
        'password': 'str'
    }

    attribute_map = {
        'base_url': 'baseUrl',
        'username': 'username',
        'password': 'password'
    }

    def __init__(self, base_url=None, username=None, password=None):  # noqa: E501
        """JiraSecretDetails - a model defined in Swagger"""  # noqa: E501
        self._base_url = None
        self._username = None
        self._password = None
        self.discriminator = None
        self.base_url = base_url
        self.username = username
        self.password = password

    @property
    def base_url(self):
        """Gets the base_url of this JiraSecretDetails.  # noqa: E501

        baseUrl to connect to jira instance  # noqa: E501

        :return: The base_url of this JiraSecretDetails.  # noqa: E501
        :rtype: str
        """
        return self._base_url

    @base_url.setter
    def base_url(self, base_url):
        """Sets the base_url of this JiraSecretDetails.

        baseUrl to connect to jira instance  # noqa: E501

        :param base_url: The base_url of this JiraSecretDetails.  # noqa: E501
        :type: str
        """
        if base_url is None:
            raise ValueError("Invalid value for `base_url`, must not be `None`")  # noqa: E501

        self._base_url = base_url

    @property
    def username(self):
        """Gets the username of this JiraSecretDetails.  # noqa: E501

        username to connect to jira instance  # noqa: E501

        :return: The username of this JiraSecretDetails.  # noqa: E501
        :rtype: str
        """
        return self._username

    @username.setter
    def username(self, username):
        """Sets the username of this JiraSecretDetails.

        username to connect to jira instance  # noqa: E501

        :param username: The username of this JiraSecretDetails.  # noqa: E501
        :type: str
        """
        if username is None:
            raise ValueError("Invalid value for `username`, must not be `None`")  # noqa: E501

        self._username = username

    @property
    def password(self):
        """Gets the password of this JiraSecretDetails.  # noqa: E501

        password to connect to jira instance  # noqa: E501

        :return: The password of this JiraSecretDetails.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this JiraSecretDetails.

        password to connect to jira instance  # noqa: E501

        :param password: The password of this JiraSecretDetails.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(JiraSecretDetails, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, JiraSecretDetails):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
