# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six
from appcenter.models.legacy_code_push_release import LegacyCodePushRelease  # noqa: F401,E501


class LegacyPatchCodePushReleaseResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'package': 'LegacyCodePushRelease'
    }

    attribute_map = {
        'package': 'package'
    }

    def __init__(self, package=None):  # noqa: E501
        """LegacyPatchCodePushReleaseResponse - a model defined in Swagger"""  # noqa: E501
        self._package = None
        self.discriminator = None
        self.package = package

    @property
    def package(self):
        """Gets the package of this LegacyPatchCodePushReleaseResponse.  # noqa: E501


        :return: The package of this LegacyPatchCodePushReleaseResponse.  # noqa: E501
        :rtype: LegacyCodePushRelease
        """
        return self._package

    @package.setter
    def package(self, package):
        """Sets the package of this LegacyPatchCodePushReleaseResponse.


        :param package: The package of this LegacyPatchCodePushReleaseResponse.  # noqa: E501
        :type: LegacyCodePushRelease
        """
        if package is None:
            raise ValueError("Invalid value for `package`, must not be `None`")  # noqa: E501

        self._package = package

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LegacyPatchCodePushReleaseResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LegacyPatchCodePushReleaseResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
