# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class NodeVersion(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'current': 'bool'
    }

    attribute_map = {
        'name': 'name',
        'current': 'current'
    }

    def __init__(self, name=None, current=None):  # noqa: E501
        """NodeVersion - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._current = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if current is not None:
            self.current = current

    @property
    def name(self):
        """Gets the name of this NodeVersion.  # noqa: E501

        The version name  # noqa: E501

        :return: The name of this NodeVersion.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this NodeVersion.

        The version name  # noqa: E501

        :param name: The name of this NodeVersion.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def current(self):
        """Gets the current of this NodeVersion.  # noqa: E501

        If the Node version is default for AppCenter  # noqa: E501

        :return: The current of this NodeVersion.  # noqa: E501
        :rtype: bool
        """
        return self._current

    @current.setter
    def current(self, current):
        """Sets the current of this NodeVersion.

        If the Node version is default for AppCenter  # noqa: E501

        :param current: The current of this NodeVersion.  # noqa: E501
        :type: bool
        """

        self._current = current

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NodeVersion, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NodeVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
