# coding: utf-8

"""
    App Center Client

    Microsoft Visual Studio App Center API  # noqa: E501

    OpenAPI spec version: preview
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from appcenter.api_client import ApiClient


class ExportApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def export_configurations_create(self, body, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_create  # noqa: E501

        Create new export configuration  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_create(body, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ExportConfiguration body: Export configurations. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: ExportConfigurationResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.export_configurations_create_with_http_info(body, owner_name, app_name, **kwargs)  # noqa: E501
        else:
            (data) = self.export_configurations_create_with_http_info(body, owner_name, app_name, **kwargs)  # noqa: E501
            return data

    def export_configurations_create_with_http_info(self, body, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_create  # noqa: E501

        Create new export configuration  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_create_with_http_info(body, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ExportConfiguration body: Export configurations. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: ExportConfigurationResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'owner_name', 'app_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method export_configurations_create" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `export_configurations_create`")  # noqa: E501
        # verify the required parameter 'owner_name' is set
        if ('owner_name' not in params or
                params['owner_name'] is None):
            raise ValueError("Missing the required parameter `owner_name` when calling `export_configurations_create`")  # noqa: E501
        # verify the required parameter 'app_name' is set
        if ('app_name' not in params or
                params['app_name'] is None):
            raise ValueError("Missing the required parameter `app_name` when calling `export_configurations_create`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'owner_name' in params:
            path_params['owner_name'] = params['owner_name']  # noqa: E501
        if 'app_name' in params:
            path_params['app_name'] = params['app_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIToken']  # noqa: E501

        return self.api_client.call_api(
            '/v0.1/apps/{owner_name}/{app_name}/export_configurations', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ExportConfigurationResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def export_configurations_delete(self, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_delete  # noqa: E501

        Delete export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_delete(export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.export_configurations_delete_with_http_info(export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
        else:
            (data) = self.export_configurations_delete_with_http_info(export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
            return data

    def export_configurations_delete_with_http_info(self, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_delete  # noqa: E501

        Delete export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_delete_with_http_info(export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['export_configuration_id', 'owner_name', 'app_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method export_configurations_delete" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'export_configuration_id' is set
        if ('export_configuration_id' not in params or
                params['export_configuration_id'] is None):
            raise ValueError("Missing the required parameter `export_configuration_id` when calling `export_configurations_delete`")  # noqa: E501
        # verify the required parameter 'owner_name' is set
        if ('owner_name' not in params or
                params['owner_name'] is None):
            raise ValueError("Missing the required parameter `owner_name` when calling `export_configurations_delete`")  # noqa: E501
        # verify the required parameter 'app_name' is set
        if ('app_name' not in params or
                params['app_name'] is None):
            raise ValueError("Missing the required parameter `app_name` when calling `export_configurations_delete`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'export_configuration_id' in params:
            path_params['export_configuration_id'] = params['export_configuration_id']  # noqa: E501
        if 'owner_name' in params:
            path_params['owner_name'] = params['owner_name']  # noqa: E501
        if 'app_name' in params:
            path_params['app_name'] = params['app_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIToken']  # noqa: E501

        return self.api_client.call_api(
            '/v0.1/apps/{owner_name}/{app_name}/export_configurations/{export_configuration_id}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def export_configurations_disable(self, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_disable  # noqa: E501

        Disable export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_disable(export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.export_configurations_disable_with_http_info(export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
        else:
            (data) = self.export_configurations_disable_with_http_info(export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
            return data

    def export_configurations_disable_with_http_info(self, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_disable  # noqa: E501

        Disable export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_disable_with_http_info(export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['export_configuration_id', 'owner_name', 'app_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method export_configurations_disable" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'export_configuration_id' is set
        if ('export_configuration_id' not in params or
                params['export_configuration_id'] is None):
            raise ValueError("Missing the required parameter `export_configuration_id` when calling `export_configurations_disable`")  # noqa: E501
        # verify the required parameter 'owner_name' is set
        if ('owner_name' not in params or
                params['owner_name'] is None):
            raise ValueError("Missing the required parameter `owner_name` when calling `export_configurations_disable`")  # noqa: E501
        # verify the required parameter 'app_name' is set
        if ('app_name' not in params or
                params['app_name'] is None):
            raise ValueError("Missing the required parameter `app_name` when calling `export_configurations_disable`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'export_configuration_id' in params:
            path_params['export_configuration_id'] = params['export_configuration_id']  # noqa: E501
        if 'owner_name' in params:
            path_params['owner_name'] = params['owner_name']  # noqa: E501
        if 'app_name' in params:
            path_params['app_name'] = params['app_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIToken']  # noqa: E501

        return self.api_client.call_api(
            '/v0.1/apps/{owner_name}/{app_name}/export_configurations/{export_configuration_id}/disable', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def export_configurations_enable(self, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_enable  # noqa: E501

        Enable export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_enable(export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.export_configurations_enable_with_http_info(export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
        else:
            (data) = self.export_configurations_enable_with_http_info(export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
            return data

    def export_configurations_enable_with_http_info(self, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_enable  # noqa: E501

        Enable export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_enable_with_http_info(export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['export_configuration_id', 'owner_name', 'app_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method export_configurations_enable" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'export_configuration_id' is set
        if ('export_configuration_id' not in params or
                params['export_configuration_id'] is None):
            raise ValueError("Missing the required parameter `export_configuration_id` when calling `export_configurations_enable`")  # noqa: E501
        # verify the required parameter 'owner_name' is set
        if ('owner_name' not in params or
                params['owner_name'] is None):
            raise ValueError("Missing the required parameter `owner_name` when calling `export_configurations_enable`")  # noqa: E501
        # verify the required parameter 'app_name' is set
        if ('app_name' not in params or
                params['app_name'] is None):
            raise ValueError("Missing the required parameter `app_name` when calling `export_configurations_enable`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'export_configuration_id' in params:
            path_params['export_configuration_id'] = params['export_configuration_id']  # noqa: E501
        if 'owner_name' in params:
            path_params['owner_name'] = params['owner_name']  # noqa: E501
        if 'app_name' in params:
            path_params['app_name'] = params['app_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIToken']  # noqa: E501

        return self.api_client.call_api(
            '/v0.1/apps/{owner_name}/{app_name}/export_configurations/{export_configuration_id}/enable', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def export_configurations_get(self, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_get  # noqa: E501

        Get export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_get(export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: ExportConfigurationResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.export_configurations_get_with_http_info(export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
        else:
            (data) = self.export_configurations_get_with_http_info(export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
            return data

    def export_configurations_get_with_http_info(self, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_get  # noqa: E501

        Get export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_get_with_http_info(export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: ExportConfigurationResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['export_configuration_id', 'owner_name', 'app_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method export_configurations_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'export_configuration_id' is set
        if ('export_configuration_id' not in params or
                params['export_configuration_id'] is None):
            raise ValueError("Missing the required parameter `export_configuration_id` when calling `export_configurations_get`")  # noqa: E501
        # verify the required parameter 'owner_name' is set
        if ('owner_name' not in params or
                params['owner_name'] is None):
            raise ValueError("Missing the required parameter `owner_name` when calling `export_configurations_get`")  # noqa: E501
        # verify the required parameter 'app_name' is set
        if ('app_name' not in params or
                params['app_name'] is None):
            raise ValueError("Missing the required parameter `app_name` when calling `export_configurations_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'export_configuration_id' in params:
            path_params['export_configuration_id'] = params['export_configuration_id']  # noqa: E501
        if 'owner_name' in params:
            path_params['owner_name'] = params['owner_name']  # noqa: E501
        if 'app_name' in params:
            path_params['app_name'] = params['app_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIToken']  # noqa: E501

        return self.api_client.call_api(
            '/v0.1/apps/{owner_name}/{app_name}/export_configurations/{export_configuration_id}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ExportConfigurationResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def export_configurations_list(self, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_list  # noqa: E501

        List export configurations.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_list(owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: ExportConfigurationListResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.export_configurations_list_with_http_info(owner_name, app_name, **kwargs)  # noqa: E501
        else:
            (data) = self.export_configurations_list_with_http_info(owner_name, app_name, **kwargs)  # noqa: E501
            return data

    def export_configurations_list_with_http_info(self, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_list  # noqa: E501

        List export configurations.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_list_with_http_info(owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: ExportConfigurationListResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['owner_name', 'app_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method export_configurations_list" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'owner_name' is set
        if ('owner_name' not in params or
                params['owner_name'] is None):
            raise ValueError("Missing the required parameter `owner_name` when calling `export_configurations_list`")  # noqa: E501
        # verify the required parameter 'app_name' is set
        if ('app_name' not in params or
                params['app_name'] is None):
            raise ValueError("Missing the required parameter `app_name` when calling `export_configurations_list`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'owner_name' in params:
            path_params['owner_name'] = params['owner_name']  # noqa: E501
        if 'app_name' in params:
            path_params['app_name'] = params['app_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIToken']  # noqa: E501

        return self.api_client.call_api(
            '/v0.1/apps/{owner_name}/{app_name}/export_configurations', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ExportConfigurationListResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def export_configurations_partial_update(self, body, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_partial_update  # noqa: E501

        Partially update export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_partial_update(body, export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ExportConfiguration body: Export configurations. (required)
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: ExportConfigurationResult
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.export_configurations_partial_update_with_http_info(body, export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
        else:
            (data) = self.export_configurations_partial_update_with_http_info(body, export_configuration_id, owner_name, app_name, **kwargs)  # noqa: E501
            return data

    def export_configurations_partial_update_with_http_info(self, body, export_configuration_id, owner_name, app_name, **kwargs):  # noqa: E501
        """export_configurations_partial_update  # noqa: E501

        Partially update export configuration.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.export_configurations_partial_update_with_http_info(body, export_configuration_id, owner_name, app_name, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param ExportConfiguration body: Export configurations. (required)
        :param str export_configuration_id: The id of the export configuration. (required)
        :param str owner_name: The name of the owner (required)
        :param str app_name: The name of the application (required)
        :return: ExportConfigurationResult
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body', 'export_configuration_id', 'owner_name', 'app_name']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method export_configurations_partial_update" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `export_configurations_partial_update`")  # noqa: E501
        # verify the required parameter 'export_configuration_id' is set
        if ('export_configuration_id' not in params or
                params['export_configuration_id'] is None):
            raise ValueError("Missing the required parameter `export_configuration_id` when calling `export_configurations_partial_update`")  # noqa: E501
        # verify the required parameter 'owner_name' is set
        if ('owner_name' not in params or
                params['owner_name'] is None):
            raise ValueError("Missing the required parameter `owner_name` when calling `export_configurations_partial_update`")  # noqa: E501
        # verify the required parameter 'app_name' is set
        if ('app_name' not in params or
                params['app_name'] is None):
            raise ValueError("Missing the required parameter `app_name` when calling `export_configurations_partial_update`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'export_configuration_id' in params:
            path_params['export_configuration_id'] = params['export_configuration_id']  # noqa: E501
        if 'owner_name' in params:
            path_params['owner_name'] = params['owner_name']  # noqa: E501
        if 'app_name' in params:
            path_params['app_name'] = params['app_name']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['APIToken']  # noqa: E501

        return self.api_client.call_api(
            '/v0.1/apps/{owner_name}/{app_name}/export_configurations/{export_configuration_id}', 'PATCH',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='ExportConfigurationResult',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
